### ISSUE TITLE
Suggestion - Include SSR section /Next JS

### ISSUE THREAD

**Issue by jon64digital** [adam-golab/react-developer-roadmap#11]
Sorry, can't do a PR because I don't know what package you've used to create the diagram, but the one thing I noticed is that Isomorphic/Universal/SSR seemed to be an obvious omission.

Great diagram though, really helping me make some choices.

**Comment by rlodina** [comment]
> I don't know what package you've used to create the diagram

https://about.draw.io   you can also install desktop version: https://about.draw.io/integrations/#integrations_offline

**Comment by adam-golab** [comment]
Actually, there is a section about SSR, it includes Next.js and After.js
![screen shot 2018-07-06 at 08 21 19](https://user-images.githubusercontent.com/20810956/42365929-221ce2b4-8100-11e8-8202-cf1851e2ef16.png)

**Comment by jon64digital** [comment]
Ah, damnit! I thought I'd checked the whole diagram. Good work.
