### ISSUE TITLE
Hope there is a multi-language version.

### ISSUE THREAD

**Issue by LinJoey5** [adam-golab/react-developer-roadmap#24]
Thanks to the author create such a clear roadmap. I am a Chinese developer who often encounters difficult-to-understand English words on the road to learning react. I hope that not only the language version of my native language, but also other developers in different languages in the world can understand how to become a react developer.

**Comment by redagavin** [comment]
I can translate the roadmap into Chinese if the author wants. @adam-golab Do you want me to create a Chinese version of the roadmap?

**Comment by adam-golab** [comment]
@redagavin Actually, there is a PR with translation #27 but I'm not sure about its quality. Could you check it and suggest changes if there are required? If you think that easier will be to open a new PR with translation then feel free to do it.

**Comment by SangKa** [comment]
Because the exist of the source file of the flowchart, it's difficlut to manage the multi-language version in one repo. I created a segregate repo for Chinese translation. Here is the [repo](https://github.com/SangKa/react-roadmap).

**Comment by adam-golab** [comment]
@zenghongtu Prepared translated version of the roadmap. I'm closing this issue in favor of #41
