### ISSUE TITLE
What is the drawing tool for the roadmap?

### ISSUE THREAD

**Issue by hooj0** [adam-golab/react-developer-roadmap#34]
What is the drawing tool for the roadmap? I feel that this drawing tool is very good and I like it very much. thx!

**Comment by adam-golab** [comment]
Hi @hooj0, there is an information about a used tool in the readme. I built the roadmap using [Draw.io](https://www.draw.io/).

**Comment by hooj0** [comment]
Hi @adam-golab , thank you very much for your answer, this is really a very good drawing software, it is really cool.
