### ISSUE TITLE
Add scaffolding tools in the build tools

### ISSUE THREAD

**Issue by zhnoah** [adam-golab/react-developer-roadmap#56]
1. Create React App [Personal must know]

2. React boilerplate [Possibilities]

3. React Starter Kit [Possibilities]

**Comment by shobhitchittora** [comment]
@zhnoah +1

**Comment by tanwei-cc** [comment]
构建打包工具集

https://github.com/tanwei-cc/frontend-dev-tools/blob/master/%E6%9E%84%E5%BB%BA%E6%89%93%E5%8C%85/index.md

**Comment by tanwei-cc** [comment]
2019 Web前端开发工具集
https://github.com/tanwei-cc/frontend-dev-tools

**Comment by tanwei-cc** [comment]
希望作者能接受我的PR
