### ISSUE TITLE
RxJS doesn't relate to MobX

### ISSUE THREAD

**Issue by capaj** [adam-golab/react-developer-roadmap#6]
RxJS is a state management solution, but it does not relate to MobX at all. It features different kind of `observables`. In fact MobX `observables` and RxJS `observables` have very little in common.

You could add MobX state tree as a state management solution related to MobX if you want.

**Comment by adam-golab** [comment]
Thanks for reporting this issue. I moved RxJS to utility libraries, so now there should be clear that RxJS and MobX are not related to each other.
