### ISSUE TITLE
To add an ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by dominguezcelada** [adam-golab/react-developer-roadmap#77]
I think it would be nice to design an ISSUE_TEMPLATE to standardize the discussions and requests of improvement in the repo.

Let me know your opinion and I would be able to draft an ISSUE_TEMPLATE.md to discuss it.

**Comment by dominguezcelada** [comment]
Hi!

I would like to follow up on this issue

**Comment by oscard0m** [comment]
Not necessary for the moment
