### ISSUE TITLE
Provide diagrams in higher resolution

### ISSUE THREAD

**Issue by d0h0** [adam-golab/react-developer-roadmap#85]
It would be great if the diagrams had better resolution to be printed out or lasered on wood.

**Comment by tanwei-cc** [comment]
Click to see the original picture

**Comment by tanwei-cc** [comment]
Web front-end development toolset
https://github.com/tanwei-cc/frontend-dev-tools/blob/master/README.en.md

**Comment by d0h0** [comment]
Cool, thanks!
